services:
  postgresql:
    container_name: customer-db2
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    volumes:
      - postgresqldb_data:/data/db/postgresql2
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kuubraucar1@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "5055:80"
volumes:
  postgresqldb_data: